---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(readr)
library(ggplot2)
day_n <- "2020-04-07"
url <- "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
data <- read.csv(url, header = TRUE)
datamle <- subset(data, location=="United Kingdom"  & date>="2020-03-14" & date<=day_n, select = -c(iso_code, continent, stringency_index, population_density:life_expectancy, new_tests:tests_units)) #display only relavent columns and the UK data only. Starting date when 10 cumulative deaths have been recorded and the end date is 2 weeks past the start of the UK lockdown to allow for any delays between redcuded transmission having an effect on mortality.
datamletot <- subset(data, location=="United Kingdom"  & date>="2020-03-14" & date<="2020-04-07", select = -c(iso_code, continent, stringency_index, population_density:life_expectancy, new_tests:tests_units))
datamle

library(lubridate)
day1 <- as.Date("2020-03-14")
dayn <- as.Date(day_n)
 
Day <- 1:as.integer(ymd(dayn) + 1 - ymd(day1))


Deathsmle <- datamle$total_deaths

ggplot(datamle) +
    geom_point(aes(Day, Deathsmle),colour = 'purple', size = 0.5) 
```

```{r}
#defining our SIRD model to be solved in the mle functions, equation ()
library(deSolve)
sird <- function(t,x,parms){
    S <- x[1]
    I <- x[2]
    R <- x[3]
    D <- x[4]

    
  with(as.list(parms),
{
    dS <- -beta*S*I/N
    dI <- beta*S*I/N - gamma*I - sigma*I
    dR <- gamma*I
    dD <- sigma*I
    res <- c(dS,dI,dR,dD)
  list(res)
})
}
```

```{r}

require(bbmle)
#  create negative likelihood functions for negbin and poisson distributions. The poisson distribution is given in equation (3-5) and the negatuve binomial function in given in equation (6-8).

sirdpois <- function(lbeta,lgamma, lsigma) {
    parms <- c(beta=plogis(lbeta), gamma=plogis(lgamma), sigma=plogis(lsigma))
    x0 <- c(S=N - 1766 , I= 1766, R=1500, D = 10)
    out <- ode(y=x0, Day, sird, parms)
    -sum(dpois(Deathsmle, lambda=out[,5], log = TRUE))
 
}

sirdnbin <- function(lbeta,lgamma, lsigma) {
    parms <- c(beta=plogis(lbeta), gamma=plogis(lgamma), sigma=plogis(lsigma))
    x0 <- c(S=N - 1766, I= 1766, R=1500, D = 10)
    out <- ode(y=x0, Day, sird, parms)
    #phi <- 1/parms['phiinv']
    -sum(dnbinom(Deathsmle, mu=out[,5], size=75, log = TRUE))

}

# minimize negative-log-likelihood using the initial parameters given in Table (2) in report

N <- 66650000

fit1 <- mle(sirdpois,
            start=list(lbeta=qlogis(0.25),
                 lgamma = qlogis(0.15),     
                lsigma = qlogis(0.001)),
            method="Nelder-Mead",
            control=list(maxit=1E5,trace=0))



fit2 <- mle(sirdnbin,
            start=list(lbeta=qlogis(0.25),
                 lgamma = qlogis(0.15),      
                lsigma= qlogis(0.001)),
            method="Nelder-Mead",
            control=list(maxit=1E5,trace=0))

           
#taking the exponential of each of the output will give us the paramater estimate we need from each distribution. Using these paramater estimates, we use eqaution (43) to calculate the R0 number.

options(scipen=999)
pars=c('beta','gamma','sigma')


summary(fit1)
theta1 <- as.numeric(c(plogis(coef(fit1)[1:3])))
                  
theta1  <- round(theta1, digits = 6)
setNames(theta1, pars)
R01 <- theta1[1]/(theta1[2] + theta1[3])
R01
summary(fit2)
theta2 <- as.numeric(c(plogis(coef(fit2)[1:3])))
 pars=c('beta','gamma','sigma')                
theta2  <- round(theta2, digits = 6)
setNames(theta2, pars)
R02 <- theta2[1]/(theta2[2] + theta2[3])
R02

```
```{r}
#plotting the estimated output against our observed data points
library(ggplot2)
parms <- c(beta=theta1[1], gamma = theta1[2], sigma = theta1[3])
times <- seq(0,25,0.1)
#setting initial values
x0 <- c(N - 1766,1766,30,10)
stateMatrix1 <- ode(y=x0, times, sird, parms) #matrix to hold the output
colnames(stateMatrix1) <- c("time","S","I","R", "D")
stateMatrix1 <- as.data.frame(stateMatrix1)

parms <- c(beta=theta2[1], gamma = theta2[2], sigma = theta2[3])
#setting initial values
x0 <- c(N - 1766,1766,30,10)
stateMatrix2 <- ode(y=x0, times, sird, parms) #matrix to hold the output
colnames(stateMatrix2) <- c("time","S","I","R", "D")
stateMatrix2 <- as.data.frame(stateMatrix2)

ggplot() + geom_line(data = stateMatrix1, aes(x = time, y = D, colour = "black"),linetype = 2) +
    geom_point(data = datamle, aes(Day, Deathsmle, colour = "red"),size = 0.75) +
  labs(
    title = "Poisson Distribution Fit",
    y = "Total Deaths",
    x = "Days since 10 cummulative deaths recorded in the UK, 14/03/20"
  )+
scale_color_identity(name = "Key",
breaks = c("black", "red"),
labels = c("Poisson Fit","Data"),
guide = "legend")+
  theme(legend.position = "bottom")
  
  ggplot() + geom_line(data = stateMatrix2, aes(x = time, y = D, colour = "purple"),linetype = 2)+
  geom_point(data = datamle, aes(Day, Deathsmle, colour = "red"),size = 0.75) +
  labs(
    title="Negative Binomial Distribution Fit",
    y = "Total Deaths",
    x = "Days since 10 cummulative deaths recorded in the UK, 14/03/20"
  )+
scale_color_identity(name = "Key",
breaks = c("purple", "red"),
labels = c("Neg Bin Fit","Data"),
guide = "legend")+
  theme(legend.position = "bottom")
```
